# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    use_sim_time: true

# Robot differential wheels base controller 
    diff_base_controller:
      type: "diff_drive_controller/DiffDriveController"
# Publishing Joint State from the real model 
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_base_controller:
  ros__parameters:
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    left_wheel_names: ["LD_joint"]
    right_wheel_names: ["RD_joint"]

    wheel_separation: 0.46
    wheel_radius: 0.161

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link

    use_stamped_vel: false
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0